export const colors = {
  DRAFT: "info",
  OPEN: "warning",
  SUBMITTED: "warning",
  PARTIALLY_APPROVED: "primary",
  FULLY_APPROVED: "primary",
  IN_PROCESS: "warning",
  REJECTED: "danger",
  VERIFIED: "success",
  AUTHORIZED: "success",
  PAID: "success",
  CLOSED: "success",
  // Lead status
  New: "warning",
  Contacted: "warning",
  Qualified: "primary",
  Unqualified: "info",
  Converted: "success",
  // opportunity stages
  Prospecting: "warning",
  Negotiation: "primary",
  Proposal_Sent: "primary",
  Closed_Won: "success",
  Closed_Lost: "info",
  Call: "warning",
  Meeting: "primary",
  Email: "info",
  Follow_Up: "warning",
  Demo: "primary",
  Presentation: "primary",
  Contract_Sent: "primary",
  Contract_Signed: "success",
  Completed: "success",
  In_Progress: "warning",
  InProgress: "warning",
  Todo: "warning",
  On_Hold: "info",
  Cancelled: "danger",
  // task status
  Pending: "warning",
  Completed: "success",
  Overdue: "danger",
};
