export const colors = {
  DRAFT: "info",
  OPEN: "warning",
  SUBMITTED: "warning",
  PARTIALLY_APPROVED: "primary",
  FULLY_APPROVED: "primary",
  IN_PROCESS: "warning",
  REJECTED: "danger",
  VERIFIED: "success",
  AUTHORIZED: "success",
  PAID: "success",
  CLOSED: "success",
  // Lead status
  New: "warning",
  Contacted: "warning",
  Qualified: "primary",
  Unqualified: "info",
  Converted: "success",
  // opportunity stages
  Prospecting: "warning",
  Negotiation: "primary",
  Proposal_Sent: "primary",
  Closed_Won: "success",
  Closed_Lost: "info",
};
